// Automatically generated by deploy.sh
// Contract addresses for Avalanche Fuji Testnet

export interface ContractAddresses {
  trashToken: string;
  testUSDC: string;
  stakeNFT: string;
  achievementNFT: string;
  emailVerifier: string;
  recyclingSystem: string;
  questSystem: string;
  trashGenesis: string;
}

export const contractAddresses: ContractAddresses = {
  trashToken: "0x343c3704248DC9143050bC618F3d1a8E28CBb9f8",
  testUSDC: "0x8bE33D76353AB764f3A7b9F45B8Eff0090a48d12",
  stakeNFT: "0xcC8179FC62F75AbF5dEABf16c39B147144ba0564",
  achievementNFT: "0x96cBD71AcE43AB693E16dF80202a7DFff9B482dC",
  emailVerifier: "0xebfd0088D27F31a611d55016CC64f8e9719dad94",
  recyclingSystem: "0xbF2cE3A7938F255d31C1032b3a53Fd6c933e5B20",
  questSystem: "0x94f1c70d4f7cb71174A68D8520A6d948b4E9409b",
  trashGenesis: "0xB4b773cDd37FDe0D431a202378Cc54b388ac1776"
};

export const networkConfig = {
  name: "Avalanche Fuji Testnet",
  chainId: 43113,
  rpcUrl: "https://api.avax-test.network/ext/bc/C/rpc",
  blockExplorer: "https://testnet.snowtrace.io"
};
