// Automatically generated by deploy.sh
// Contract addresses for Avalanche Fuji Testnet

export interface ContractAddresses {
  trashToken: string;
  testUSDC: string;
  stakeNFT: string;
  achievementNFT: string;
  emailVerifier: string;
  recyclingSystem: string;
  questSystem: string;
}

export const contractAddresses: ContractAddresses = {
  trashToken: "0xb8eBb52b8AffC07Bb8EC67b9230E19989A907CAf",
  testUSDC: "0x161CFA4198bF7D7823D364EEFbB7e7052F815766",
  stakeNFT: "0xf4A26F16598f9e3B010703fDf4697F067463F84A",
  achievementNFT: "0x1C5A0a5E6f08125bc46253ABfD386Afb619D94D1",
  emailVerifier: "0xA0Affc621a9D663A6D3726BaEaa712A7Ed890c9C",
  recyclingSystem: "0x1b9Fb4f3d9F8e326F22a3429dc81C491EA620F3C",
  questSystem: "0x8Bc26cdbd51598030b0E81566b9602122F90b920"
};

export const networkConfig = {
  name: "Avalanche Fuji Testnet",
  chainId: 43113,
  rpcUrl: "https://api.avax-test.network/ext/bc/C/rpc",
  blockExplorer: "https://testnet.snowtrace.io"
};
