import React, { useState, useEffect, useRef } from 'react';
import { motion, useInView } from 'framer-motion';
import Section from '../ui/Section';
import Card from '../ui/Card';
import Button from '../ui/Button';

const HowItWorks: React.FC = () => {
  const [activeStep, setActiveStep] = useState(0);
  const [userInteracted, setUserInteracted] = useState(false);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const intervalRef = useRef<any>(null);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const timeoutRef = useRef<any>(null);
  const sectionRef = useRef<HTMLDivElement>(null);
  const isInView = useInView(sectionRef, { once: false, amount: 0.3 });
  
  // Auto-advance through steps only when in view and until user interaction
  useEffect(() => {
    // Clear any existing intervals/timeouts when dependencies change
    if (intervalRef.current) {
      clearInterval(intervalRef.current);
      intervalRef.current = null;
    }
    
    if (timeoutRef.current) {
      clearTimeout(timeoutRef.current);
      timeoutRef.current = null;
    }
    
    if (isInView && !userInteracted) {
      // Start a timeout to delay the first animation
      timeoutRef.current = setTimeout(() => {
        // Start the interval for auto-advancing
        intervalRef.current = setInterval(() => {
          setActiveStep((prevStep) => (prevStep + 1) % 3);
        }, 5000); // Change step every 5 seconds
      }, 1000); // 1 second delay before starting animation
    }
    
    return () => {
      if (intervalRef.current) {
        clearInterval(intervalRef.current);
      }
      if (timeoutRef.current) {
        clearTimeout(timeoutRef.current);
      }
    };
  }, [userInteracted, isInView]);
  
  // Handle user interaction
  const handleInteraction = (index: number) => {
    if (!userInteracted) {
      setUserInteracted(true);
      if (intervalRef.current) {
        clearInterval(intervalRef.current);
        intervalRef.current = null;
      }
      if (timeoutRef.current) {
        clearTimeout(timeoutRef.current);
        timeoutRef.current = null;
      }
    }
    setActiveStep(index);
  };
  
  const steps = [
    {
      title: "1. Decentralized Ownership",
      description: "Stake capital to fund Smart Can deployment and earn recurring revenue",
      details: "Stakeholders fund the manufacturing and deployment of Decycle Smart Can units through a crowdfunding structure. In return, shareholders receive a recurring, verified share of the revenue generated by that machine. This provides stable, asset-backed yield tied to measurable environmental impact.",
      icon: (
        <svg xmlns="http://www.w3.org/2000/svg" className="h-10 w-10 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" />
        </svg>
      ),
      benefit: "Asset-backed yield from physical infrastructure",
      color: "from-forest to-forest-light"
    },
    {
      title: "2. Gamified Recycling",
      description: "AI-powered Smart Cans instantly identify materials and reward users",
      details: "Our Smart Cans use AI and IoT sensors to instantly identify and weigh deposited materials. Citizens participate in the Recycle-to-Earn model, receiving rewards (Trash Tokens/Credits) for every deposit. This transforms recycling from a chore into an incentivized, high-engagement activity.",
      icon: (
        <svg xmlns="http://www.w3.org/2000/svg" className="h-10 w-10 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 3v2m6-2v2M9 19v2m6-2v2M5 9H3m2 6H3m18-6h-2m2 6h-2M7 19h10a2 2 0 002-2V7a2 2 0 00-2-2H7a2 2 0 00-2 2v10a2 2 0 002 2zM9 9h6v6H9V9z" />
        </svg>
      ),
      benefit: "Instant rewards for verified recycling",
      color: "from-sky to-sky-light"
    },
    {
      title: "3. Guaranteed Revenue",
      description: "Verified collectors purchase sorted materials at fixed rates",
      details: "Every deposit generates verifiable, on-chain data about material type and volume, guaranteeing quality and provenance. Verified waste collectors or buyers purchase the sorted material from Smart Cans at a discounted, fixed rate. They profit from the efficiency of sorted material (arbitrage), ensuring continuous, guaranteed off-take that locks in the system's revenue.",
      icon: (
        <svg xmlns="http://www.w3.org/2000/svg" className="h-10 w-10 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
      ),
      benefit: "Continuous revenue stream from verified off-take",
      color: "from-electric to-electric-light"
    }
  ];

  // Handle click anywhere on the component
  const handleComponentClick = () => {
    if (!userInteracted) {
      setUserInteracted(true);
      if (intervalRef.current) {
        clearInterval(intervalRef.current);
        intervalRef.current = null;
      }
      if (timeoutRef.current) {
        clearTimeout(timeoutRef.current);
        timeoutRef.current = null;
      }
    }
  };

  return (
    <Section id="how-it-works" bgColor="bg-gradient-to-b from-white to-gray-50" className="pt-0 -mt-8 md:-mt-28">
      <div ref={sectionRef} onClick={handleComponentClick} className="w-full">

      {/* Interactive Process Flow */}
      <div className="mb-8 md:mb-16">
        {/* Desktop Steps - Horizontal */}
        <motion.div 
          className="relative hidden md:grid md:grid-cols-3 gap-0"
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5, delay: 0.2 }}
        >
          {/* Progress Bar - Desktop */}
          <div className="absolute top-1/2 left-0 right-0 h-1 bg-gray-200 -translate-y-1/2 z-0"></div>
          <div 
            className="absolute top-1/2 left-0 h-1 bg-electric -translate-y-1/2 z-0 transition-all duration-500"
            style={{ width: `${(activeStep + 1) * (100/3)}%` }}
          ></div>
          
          {steps.map((step, index) => (
            <div 
              key={index}
              className="w-auto flex flex-col items-center"
            >
              <button
                onClick={() => handleInteraction(index)}
                className={`relative z-10 w-14 h-14 rounded-full flex items-center justify-center transition-all duration-300 ${
                  index <= activeStep 
                    ? `bg-gradient-to-br ${step.color} shadow-lg` 
                    : 'bg-gray-200'
                }`}
              >
                {index < activeStep ? (
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                  </svg>
                ) : (
                  <span className={index === activeStep ? "text-white" : "text-gray-500"}>
                    {index + 1}
                  </span>
                )}
              </button>
              <p className={`mt-2 text-sm font-medium text-center transition-colors duration-300 ${
                index <= activeStep ? 'text-forest' : 'text-gray-500'
              }`}>
                {step.title.split('. ')[1]?.split(' ')[0] || step.title.split(' ')[0]}
              </p>
            </div>
          ))}
        </motion.div>
        
        {/* Mobile Steps - Vertical Progress */}
        <div className="md:hidden">
          <div className="flex justify-between items-center mb-4">
            <h3 className="text-xl font-bold text-forest">How It Works</h3>
            <div className="text-sm font-medium text-slate">
              Step {activeStep + 1} of {steps.length}
            </div>
          </div>
          
          {/* Mobile Progress Bar */}
          <div className="relative h-2 w-full bg-gray-200 rounded-full mb-6">
            <div 
              className="absolute h-2 bg-electric rounded-full transition-all duration-500"
              style={{ width: `${(activeStep + 1) * (100/3)}%` }}
            ></div>
          </div>
          
          {/* Mobile Step Indicator */}
          <div className="flex justify-center mb-4">
            <button
              className={`relative z-10 w-16 h-16 rounded-full flex items-center justify-center transition-all duration-300 bg-gradient-to-br ${steps[activeStep].color} shadow-lg`}
            >
              {steps[activeStep].icon}
            </button>
          </div>
          
          <h4 className="text-center text-lg font-bold text-forest mb-2">
            {steps[activeStep].title}
          </h4>
        </div>
      </div>

      {/* Active Step Details */}
      <motion.div
        key={activeStep}
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        transition={{ duration: 0.3 }}
        className="relative"
      >
        {/* Desktop Layout - Side by Side */}
        <div className="hidden lg:grid lg:grid-cols-5 gap-8 items-start">
          {/* Visual Element */}
          <div className="lg:col-span-2">
            <div className={`relative rounded-2xl overflow-hidden bg-gradient-to-br ${steps[activeStep].color} p-8 h-[400px] flex items-center justify-center shadow-xl`}>
              {/* Background Elements */}
              <div className="absolute top-0 right-0 w-40 h-40 bg-white/10 rounded-full -translate-x-10 -translate-y-20 blur-md"></div>
              <div className="absolute bottom-0 left-0 w-40 h-40 bg-black/10 rounded-full translate-x-5 translate-y-10 blur-md"></div>
              
              {/* Icon Container */}
              <div className="relative z-10 flex flex-col items-center">
                <div className="w-32 h-32 rounded-full bg-white/20 backdrop-blur-sm flex items-center justify-center mb-6 mx-auto">
                  <div className="w-24 h-24 rounded-full bg-white/30 backdrop-blur-sm flex items-center justify-center">
                    <div className="w-16 h-16 rounded-full bg-electric flex items-center justify-center shadow-lg">
                      {steps[activeStep].icon}
                    </div>
                  </div>
                </div>
                
                <div className="bg-white/20 backdrop-blur-sm rounded-lg p-4 w-full max-w-xs mx-auto h-16">
                  <p className="text-white text-center font-medium flex items-center justify-center h-full">
                    {steps[activeStep].benefit}
                  </p>
                </div>
              </div>
            </div>
          </div>
          
          {/* Content */}
          <div className="lg:col-span-3">
            <Card className="p-8 rounded-xl border border-gray-100 shadow-xl bg-white/90 backdrop-blur-sm flex flex-col h-[400px]" padding="none" shadow={true} border={true}>
              <div className="flex-grow">
                <h3 className="text-2xl font-bold text-forest mb-3">{steps[activeStep].title}</h3>
                <p className="text-lg font-medium text-charcoal mb-4">{steps[activeStep].description}</p>
                <p className="text-slate">{steps[activeStep].details}</p>
              </div>
              
              <div className="flex gap-3 mt-6 mb-2">
                <Button 
                  onClick={() => {
                    handleInteraction(Math.max(0, activeStep - 1));
                  }}
                  disabled={activeStep === 0}
                  variant="outline"
                  className={activeStep === 0 ? "opacity-50 cursor-not-allowed" : ""}
                >
                  Previous Step
                </Button>
                <Button 
                  onClick={() => {
                    handleInteraction(Math.min(steps.length - 1, activeStep + 1));
                  }}
                  disabled={activeStep === steps.length - 1}
                  className={activeStep === steps.length - 1 ? "opacity-50 cursor-not-allowed" : ""}
                >
                  Next Step
                </Button>
              </div>
            </Card>
          </div>
        </div>
        
        {/* Mobile Layout - Stacked with fixed height */}
        <div className="lg:hidden">
          {/* Content Card - Fixed height */}
          <Card className="p-6 rounded-xl border border-gray-100 shadow-xl bg-white/90 backdrop-blur-sm mb-6 h-[320px] flex flex-col" padding="none" shadow={true} border={true}>
            <div className="flex-grow" style={{ height: "240px" }}>
              <p className="text-lg font-medium text-charcoal mb-3">{steps[activeStep].description}</p>
              <p className="text-slate text-sm line-clamp-6">{steps[activeStep].details}</p>
            </div>
            
            {/* Benefit Tag - Fixed height and width */}
            <div className="mt-4 flex">
              <div className={`px-4 py-2 bg-gradient-to-r ${steps[activeStep].color} text-white text-sm font-medium h-10 flex items-center`}>
                {steps[activeStep].benefit}
              </div>
            </div>
          </Card>
          
          {/* Navigation Buttons */}
          <div className="flex gap-3 mt-4 mb-4">
            <Button 
              onClick={() => {
                handleInteraction(Math.max(0, activeStep - 1));
              }}
              disabled={activeStep === 0}
              variant="outline"
              size="sm"
              className={`flex-1 ${activeStep === 0 ? "opacity-50 cursor-not-allowed" : ""}`}
            >
              Previous
            </Button>
            <Button 
              onClick={() => {
                handleInteraction(Math.min(steps.length - 1, activeStep + 1));
              }}
              disabled={activeStep === steps.length - 1}
              size="sm"
              className={`flex-1 ${activeStep === steps.length - 1 ? "opacity-50 cursor-not-allowed" : ""}`}
            >
              Next
            </Button>
          </div>
        </div>
      </motion.div>
      </div>
    </Section>
  );
};

export default HowItWorks;
